#!/bin/sh
# -*- coding: us-ascii -*-
# vim:ts=4:sw=4:softtabstop=4:smarttab:expandtab
# try and keep this pure bourne shell
# minimal clone of raspberry tool vcgencmd
# for use with Android rpicheck on;
#   Generic Linux, Armbian, Odroid, Pine64, Rock64 and other SBCs
# Does not fully implement Raspberry Pi version, silently exits
# on unhandled parameters. See README.md for debugging tips.

command=$1
case ${1} in
    measure_clock)
        case ${2} in
            arm)
                # awk is probably overkill....
                echo 'frequency(45)=1500000000' # 1.5 GHz
                exit
            ;;
            core)
                value=$(( RANDOM % 100 ))
                echo 'frequency(1)=$value''C'
                exit
            ;;
        # TODO anything else thrown an error/debug
        esac
        exit
        ;;
    measure_temp)
        # awk is probably overkill....
        # NOTE RasPi Check expects floating point result, integer result displays as 0 degrees in RasPi Check v1.8.12
		value=$(( RANDOM % 100 ))
		echo "frequency(1)="${value}"'C"
        exit
        ;;
    measure_volts)
        case ${2} in
            core)
                value=0  # TODO / FIXME
                echo 'volt='${value}'.0000V'
                exit
            ;;
        # TODO anything else thrown an error/debug
        esac
        ;;
    get_lcd_info)
		echo '1920 1080 32 60'
		exit
esac
